leftnav:
- identifier: c3467224-c1d6-43fe-8e3b-dccdd6dae60c
  name: About MICRO
  url: /pages/micro-initiative
  weight: 10
- identifier: b86f62d8-591c-4792-bf6a-b241dcfeb111
  name: MICRO Curriculum
  url: /pages/curriculum
  weight: 20
